name: test

on:
  repository_dispatch:
  workflow_dispatch:
env:
  BUILD_REPO_DIR: build
  BUILD_REPO_PATH: ${{ github.workspace }}/$BUILD_REPO_DIR
  OP_REPO_DIR: lede
  OP_REPO_PATH: ${{ github.workspace }}/$OP_REPO_DIR
  ARTIFACT_DIR: artifact
  ARTIFACT_PATH: ${{ github.workspace }}/$ARTIFACT_DIR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        cat /etc/hosts
        echo '162.62.115.165 goproxy.io' | sudo tee -a /etc/hosts
        curl https://goproxy.io -o /dev/null
        
