name: test

on:
  repository_dispatch:
  workflow_dispatch:
env:
  BUILD_REPO_DIR: build
  BUILD_REPO_PATH: ${{ github.workspace }}/$BUILD_REPO_DIR
  OP_REPO_DIR: lede
  OP_REPO_PATH: ${{ github.workspace }}/$OP_REPO_DIR
  ARTIFACT_DIR: artifact
  ARTIFACT_PATH: ${{ github.workspace }}/$ARTIFACT_DIR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
        du -h --max-depth=1 /usr/share/dotnet
        du -h --max-depth=1 /usr/local/lib/android
        du -h --max-depth=1  /opt/az
        du -h --max-depth=1 /usr/share/php
        du -h --max-depth=1 /etc/mysql
