name: test

on:
  repository_dispatch:
  workflow_dispatch:
env:
  BUILD_REPO_DIR: build
  BUILD_REPO_PATH: ${{ github.workspace }}/$BUILD_REPO_DIR
  OP_REPO_DIR: lede
  OP_REPO_PATH: ${{ github.workspace }}/$OP_REPO_DIR
  ARTIFACT_DIR: artifact
  ARTIFACT_PATH: ${{ github.workspace }}/$ARTIFACT_DIR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo | openssl s_client -servername goproxy.io -connect goproxy.io:443 2>/dev/null | openssl x509 -text
        echo | openssl s_client -servername goproxy.cn -connect goproxy.cn:443 2>/dev/null | openssl x509 -text
        curl -v https://goproxy.cn/
