name: test

on:
  repository_dispatch:
  workflow_dispatch:
env:
  BUILD_REPO_DIR: build
  BUILD_REPO_PATH: ${{ github.workspace }}/$BUILD_REPO_DIR
  OP_REPO_DIR: lede
  OP_REPO_PATH: ${{ github.workspace }}/$OP_REPO_DIR
  ARTIFACT_DIR: artifact
  ARTIFACT_PATH: ${{ github.workspace }}/$ARTIFACT_DIR
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: test
      run: |
        echo BUILD_REPO_PATH=$BUILD_REPO_PATH
        echo OP_REPO_PATH=$OP_REPO_PATH
        echo ARTIFACT_PATH=$ARTIFACT_PATH
        apt search ca-certificates
        sudo update-ca-certificates
        curl -v https://goproxy.io/github.com/ghodss/yaml/@v/
